version: "3.8"

services:
    blog:
        build: 
            context: ./code
        image: blog-post
        container_name: blog-container
        volumes: 
            - ./code:/app:ro
        ports: 
            - "3000:8080"